create table if not exists public.resource_bookings (
  id bigint generated by default as identity primary key,
  resource_id text not null,
  booking_date date not null,
  booking_time time not null,
  duration text not null default '1h',
  note text,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists resource_bookings_resource_date_key
  on public.resource_bookings (resource_id, booking_date);

alter table public.resource_bookings enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'resource_bookings'
      and policyname = 'resource_bookings_select_authenticated'
  ) then
    create policy resource_bookings_select_authenticated
      on public.resource_bookings
      for select
      to authenticated
      using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'resource_bookings'
      and policyname = 'resource_bookings_insert_own'
  ) then
    create policy resource_bookings_insert_own
      on public.resource_bookings
      for insert
      to authenticated
      with check (auth.uid() = user_id);
  end if;

x  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' 
      and tablename = 'resource_bookings'
      and policyname = 'resource_bookings_delete_own'
  ) then
    create policy resource_bookings_delete_own
      on public.resource_bookings
      for delete
      to authenticated
      using (auth.uid() = user_id);
  end if;
end
$$;
